Bugfix: Use step variable instead of step decorator
Previously, this would fail in __exit__ with
AttributeError: 'function' object has no attribute 'sentence'

To do this, the wait_for_content API had to be changed and
now requires step as the first parameter.